apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}
data:
  DRUID_HOST: "{{ .Values.druid_service.DRUID_HOST }}"
  DRUID_PORT: "{{ .Values.druid_service.DRUID_PORT }}"
  