---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels: 
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        imagePullPolicy: Always
        env:
        - name: druid_host
          valueFrom:
            configMapKeyRef:
              name: "{{ .Chart.Name }}-config"
              key: DRUID_HOST
        - name: druid_port
          valueFrom:
            configMapKeyRef:
              name: "{{ .Chart.Name }}-config"
              key: DRUID_PORT
        ports:
        - containerPort: 3000

---
apiVersion: v1 
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.targetport }}
  selector:
    app: {{ .Chart.Name }}
