apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
  labels:
    app: {{ .Chart.Name }}
data:
  DRUID_HOST: "{{ .Values.druid_service.DRUID_HOST }}"
  DRUID_PORT: "{{ .Values.druid_service.DRUID_PORT }}"
  KAFKA_HOST: "{{ .Values.kafka_service.KAFKA_HOST }}"
  KAFKA_PORT: "{{ .Values.kafka_service.KAFKA_PORT }}"
  KAFKA_TOPIC_CREATE: "{{ .Values.kafka_service.KAFKA_TOPIC_CREATE }}"
  POSTGRES_HOST: "{{ .Values.postgres_service.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.postgres_service.POSTGRES_PORT }}"
  POSTGRES_DATABASE: "{{ .Values.postgres_service.POSTGRES_DATABASE }}"
  POSTGRES_USERNAME: "{{ .Values.postgres_service.POSTGRES_USERNAME }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres_service.POSTGRES_PASSWORD }}"

  